# Generated by Django 3.1.6 on 2021-02-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='profileuser',
            name='tests_performed',
            field=models.ManyToManyField(blank=True, related_name='user_result_test', to='api.ResultTest'),
        ),
        migrations.AddField(
            model_name='resulttest',
            name='points_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='approved_courses',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='approved_courses',
            field=models.ManyToManyField(blank=True, related_name='user_result_contest', to='api.ResultContest'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_re',
            field=models.FileField(upload_to='uploads/resources/'),
        ),
    ]
