# Generated by Django 3.1.6 on 2021-02-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativequestion',
            options={'verbose_name': 'Curso - Alternativa', 'verbose_name_plural': 'Curso - Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='alternativequestiontest',
            options={'verbose_name': 'Test - Alternativa', 'verbose_name_plural': 'Test - Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='answerquestion',
            options={'verbose_name': 'Curso - Respuesta', 'verbose_name_plural': 'Cursos - Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='answertest',
            options={'verbose_name': 'Test - Respuesta', 'verbose_name_plural': 'Test - Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='prerequisite',
            options={'verbose_name': 'Curso - Pre requisito', 'verbose_name_plural': 'Cursos - Pre requisitos'},
        ),
        migrations.AlterModelOptions(
            name='questioncourse',
            options={'verbose_name': 'Curso - Pregunta', 'verbose_name_plural': 'Cursos - Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='questiontest',
            options={'verbose_name': 'Test - Pregunta', 'verbose_name_plural': 'Test - Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Curso - Recurso', 'verbose_name_plural': 'Cursos -Recursos'},
        ),
        migrations.AlterModelOptions(
            name='resultcontest',
            options={'verbose_name': 'Curso - Resultado de cuestionario', 'verbose_name_plural': 'Cursos - Resultados de cuestionarios'},
        ),
        migrations.AlterModelOptions(
            name='resulttest',
            options={'verbose_name': 'Test - Resultado', 'verbose_name_plural': 'Test - Resultados'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Curso - Video', 'verbose_name_plural': 'Cursos - Videos'},
        ),
    ]
