# Generated by Django 3.1.6 on 2021-02-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210217_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'Usuario - Perfil', 'verbose_name_plural': 'Usuarios - Perfiles'},
        ),
        migrations.AddField(
            model_name='user',
            name='initial_test_performed',
            field=models.BooleanField(default=False),
        ),
    ]
