# Generated by Django 3.1.6 on 2021-02-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210219_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativequestion',
            options={'ordering': ['created'], 'verbose_name': 'Curso - Alternativa', 'verbose_name_plural': 'Curso - Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='alternativequestiontest',
            options={'ordering': ['created'], 'verbose_name': 'Test - Alternativa', 'verbose_name_plural': 'Test - Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='questioncourse',
            options={'ordering': ['created'], 'verbose_name': 'Curso - Pregunta', 'verbose_name_plural': 'Cursos - Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='questiontest',
            options={'ordering': ['created'], 'verbose_name': 'Test - Pregunta', 'verbose_name_plural': 'Test - Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['created'], 'verbose_name': 'Curso - Recurso', 'verbose_name_plural': 'Cursos -Recursos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['created'], 'verbose_name': 'Curso - Video', 'verbose_name_plural': 'Cursos - Videos'},
        ),
        migrations.AddField(
            model_name='resultcontest',
            name='califitacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttest',
            name='points_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
