# Generated by Django 3.1.6 on 2021-02-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210222_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultcontest',
            old_name='califitacion',
            new_name='calification',
        ),
    ]
